# Generated by Django 4.0.5 on 2022-06-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teitter_link',
            new_name='twitter_link',
        ),
    ]
