# Generated by Django 4.0.5 on 2022-06-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_car_photo_alter_car_car_photo1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fule_type',
            new_name='fuele_type',
        ),
    ]
