# Generated by Django 4.0.5 on 2022-06-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_fule_type_car_fuele_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='tranmission',
            new_name='transmission',
        ),
    ]
